CREATE DATABASE IF NOT EXISTS blog CHARACTER SET 'utf8';
CREATE TABLE IF NOT EXISTS titre (
id_titre INT(3) NOT NULL AUTO_INCREMENT,
titre VARCHAR(20) NOT NULL,
PRIMARY KEY (id_titre)
)ENGINE=InnoDB CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS commentaire (
id_commentaire INT(3) NOT NULL AUTO_INCREMENT,
commentaire VARCHAR(20) NOT NULL,
PRIMARY KEY (id_commentaire)
)ENGINE=InnoDB CHARSET=utf8 ;

CREATE TABLE IF NOT EXISTS image (
id_image INT(3) NOT NULL AUTO_INCREMENT,
nom_image VARCHAR( 50 ) NOT NULL ,
taille_image VARCHAR( 25 ) NOT NULL ,
type_image VARCHAR( 25 ) NOT NULL ,
image_desc VARCHAR( 100 ) NOT NULL ,
image_blob BLOB NOT NULL ,
PRIMARY KEY (id_image)
)ENGINE=InnoDB CHARSET=utf8 ;
